version: '3.1'

services:
  database:
    image: mongo:5.0.0
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: pokedexDB
    volumes:
      - ./database:/data/db
